export const accounts = [
  {
    label: "Alicia Koch",
    email: "alicia@example.com",
    icon: "A",
  },
  {
    label: "Acme Inc.",
    email: "info@acme.com",
    icon: "A",
  },
]

export const mails = [
  {
    id: "1",
    name: "William Smith",
    email: "williamsmith@example.com",
    subject: "New project proposal",
    text: "Hey, I've got a great idea for a new project. Can we discuss it?",
    date: "2023-10-22T09:00:00",
    read: true,
    labels: ["work"],
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarahjohnson@example.com",
    subject: "Meeting rescheduled",
    text: "The team meeting has been moved to 3 PM. Please confirm your attendance.",
    date: "2023-10-22T10:30:00",
    read: false,
    labels: ["important", "work"],
  },
  {
    id: "3",
    name: "James Lee",
    email: "jameslee@example.com",
    subject: "Weekend plans",
    text: "Are you free this weekend? Thinking of organizing a small get-together.",
    date: "2023-10-21T18:45:00",
    read: true,
    labels: ["personal"],
  },
  {
    id: "4",
    name: "Emma Davis",
    email: "emmadavis@example.com",
    subject: "Project update required",
    text: "Please send me an update on the current status of the XYZ project by EOD.",
    date: "2023-10-21T14:15:00",
    read: false,
    labels: ["work", "urgent"],
  },
  {
    id: "5",
    name: "Michael Brown",
    email: "michaelbrown@example.com",
    subject: "Happy Birthday!",
    text: "Wishing you a fantastic birthday filled with joy and laughter!",
    date: "2023-10-20T00:00:00",
    read: true,
    labels: ["personal"],
  },
]